context('External validity of country names')

name_of <- function(iso3c) countrycode(iso3c, 'iso3c', 'country.name', warn = TRUE)

test_that('a variety of country names yield correct iso3c codes', {
    expect_equal(name_of('ABW'), 'Aruba')
    expect_equal(name_of('AFG'), 'Afghanistan')
    expect_equal(name_of('AGO'), 'Angola')
    expect_equal(name_of('AIA'), 'Anguilla')
    expect_equal(name_of('ALA'), 'Aland Islands')
    expect_equal(name_of('ALB'), 'Albania')
    expect_equal(name_of('AND'), 'Andorra')
    expect_equal(name_of('ARE'), 'United Arab Emirates')
    expect_equal(name_of('ARG'), 'Argentina')
    expect_equal(name_of('ARM'), 'Armenia')
    expect_equal(name_of('ASM'), 'American Samoa')
    expect_equal(name_of('ATA'), 'Antarctica')
    expect_equal(name_of('ATF'), 'French Southern Territories')
    expect_equal(name_of('ATG'), 'Antigua and Barbuda')
    expect_equal(name_of('AUS'), 'Australia')
    expect_equal(name_of('AUT'), 'Austria')
    expect_equal(name_of('AZE'), 'Azerbaijan')
    expect_equal(name_of('BDI'), 'Burundi')
    expect_equal(name_of('BEL'), 'Belgium')
    expect_equal(name_of('BEN'), 'Benin')
    expect_equal(name_of('BES'), 'Bonaire, Sint Eustatius and Saba')
    expect_equal(name_of('BFA'), 'Burkina Faso')
    expect_equal(name_of('BGD'), 'Bangladesh')
    expect_equal(name_of('BGR'), 'Bulgaria')
    expect_equal(name_of('BHR'), 'Bahrain')
    expect_equal(name_of('BHS'), 'Bahamas')
    expect_equal(name_of('BIH'), 'Bosnia and Herzegovina')
    expect_equal(name_of('BLM'), 'Saint Barthelemy')
    expect_equal(name_of('BLR'), 'Belarus')
    expect_equal(name_of('BLZ'), 'Belize')
    expect_equal(name_of('BMU'), 'Bermuda')
    expect_equal(name_of('BOL'), 'Bolivia, Plurinational State of')
    expect_equal(name_of('BRA'), 'Brazil')
    expect_equal(name_of('BRB'), 'Barbados')
    expect_equal(name_of('BRN'), 'Brunei Darussalam')
    expect_equal(name_of('BTN'), 'Bhutan')
    expect_equal(name_of('BVT'), 'Bouvet Island')
    expect_equal(name_of('BWA'), 'Botswana')
    expect_equal(name_of('CAF'), 'Central African Republic')
    expect_equal(name_of('CAN'), 'Canada')
    expect_equal(name_of('CCK'), 'Cocos (Keeling) Islands')
    expect_equal(name_of('CHE'), 'Switzerland')
    expect_equal(name_of('CHL'), 'Chile')
    expect_equal(name_of('CHN'), 'China')
    expect_equal(name_of('CIV'), 'Cote d\'Ivoire')
    expect_equal(name_of('CMR'), 'Cameroon')
    expect_equal(name_of('COD'), 'Congo, the Democratic Republic of the')
    expect_equal(name_of('COG'), 'Congo')
    expect_equal(name_of('COK'), 'Cook Islands')
    expect_equal(name_of('COL'), 'Colombia')
    expect_equal(name_of('COM'), 'Comoros')
    expect_equal(name_of('CPV'), 'Cabo Verde')
    expect_equal(name_of('CRI'), 'Costa Rica')
    expect_equal(name_of('CUB'), 'Cuba')
    expect_equal(name_of('CUW'), 'Curacao')
    expect_equal(name_of('CXR'), 'Christmas Island')
    expect_equal(name_of('CYM'), 'Cayman Islands')
    expect_equal(name_of('CYP'), 'Cyprus')
    expect_equal(name_of('CZE'), 'Czech Republic')
    expect_equal(name_of('DEU'), 'Germany')
    expect_equal(name_of('DJI'), 'Djibouti')
    expect_equal(name_of('DMA'), 'Dominica')
    expect_equal(name_of('DNK'), 'Denmark')
    expect_equal(name_of('DOM'), 'Dominican Republic')
    expect_equal(name_of('DZA'), 'Algeria')
    expect_equal(name_of('ECU'), 'Ecuador')
    expect_equal(name_of('EGY'), 'Egypt')
    expect_equal(name_of('ERI'), 'Eritrea')
    expect_equal(name_of('ESH'), 'Western Sahara')
    expect_equal(name_of('ESP'), 'Spain')
    expect_equal(name_of('EST'), 'Estonia')
    expect_equal(name_of('ETH'), 'Ethiopia')
    expect_equal(name_of('FIN'), 'Finland')
    expect_equal(name_of('FJI'), 'Fiji')
    expect_equal(name_of('FLK'), 'Falkland Islands (Malvinas)')
    expect_equal(name_of('FRA'), 'France')
    expect_equal(name_of('FRO'), 'Faroe Islands')
    expect_equal(name_of('FSM'), 'Micronesia, Federated States of')
    expect_equal(name_of('GAB'), 'Gabon')
    expect_equal(name_of('GBR'), 'United Kingdom')
    expect_equal(name_of('GEO'), 'Georgia')
    expect_equal(name_of('GGY'), 'Guernsey')
    expect_equal(name_of('GHA'), 'Ghana')
    expect_equal(name_of('GIB'), 'Gibraltar')
    expect_equal(name_of('GIN'), 'Guinea')
    expect_equal(name_of('GLP'), 'Guadeloupe')
    expect_equal(name_of('GMB'), 'Gambia')
    expect_equal(name_of('GNB'), 'Guinea-Bissau')
    expect_equal(name_of('GNQ'), 'Equatorial Guinea')
    expect_equal(name_of('GRC'), 'Greece')
    expect_equal(name_of('GRD'), 'Grenada')
    expect_equal(name_of('GRL'), 'Greenland')
    expect_equal(name_of('GTM'), 'Guatemala')
    expect_equal(name_of('GUF'), 'French Guiana')
    expect_equal(name_of('GUM'), 'Guam')
    expect_equal(name_of('GUY'), 'Guyana')
    expect_equal(name_of('HKG'), 'Hong Kong')
    expect_equal(name_of('HMD'), 'Heard Island and McDonald Islands')
    expect_equal(name_of('HND'), 'Honduras')
    expect_equal(name_of('HRV'), 'Croatia')
    expect_equal(name_of('HTI'), 'Haiti')
    expect_equal(name_of('HUN'), 'Hungary')
    expect_equal(name_of('IDN'), 'Indonesia')
    expect_equal(name_of('IMN'), 'Isle of Man')
    expect_equal(name_of('IND'), 'India')
    expect_equal(name_of('IOT'), 'British Indian Ocean Territory')
    expect_equal(name_of('IRL'), 'Ireland')
    expect_equal(name_of('IRN'), 'Iran, Islamic Republic of')
    expect_equal(name_of('IRQ'), 'Iraq')
    expect_equal(name_of('ISL'), 'Iceland')
    expect_equal(name_of('ISR'), 'Israel')
    expect_equal(name_of('ITA'), 'Italy')
    expect_equal(name_of('JAM'), 'Jamaica')
    expect_equal(name_of('JEY'), 'Jersey')
    expect_equal(name_of('JOR'), 'Jordan')
    expect_equal(name_of('JPN'), 'Japan')
    expect_equal(name_of('KAZ'), 'Kazakhstan')
    expect_equal(name_of('KEN'), 'Kenya')
    expect_equal(name_of('KGZ'), 'Kyrgyzstan')
    expect_equal(name_of('KHM'), 'Cambodia')
    expect_equal(name_of('KIR'), 'Kiribati')
    expect_equal(name_of('KNA'), 'Saint Kitts and Nevis')
    expect_equal(name_of('KOR'), 'Korea, Republic of')
    expect_equal(name_of('KWT'), 'Kuwait')
    expect_equal(name_of('LAO'), 'Lao People\'s Democratic Republic')
    expect_equal(name_of('LBN'), 'Lebanon')
    expect_equal(name_of('LBR'), 'Liberia')
    expect_equal(name_of('LBY'), 'Libya')
    expect_equal(name_of('LCA'), 'Saint Lucia')
    expect_equal(name_of('LIE'), 'Liechtenstein')
    expect_equal(name_of('LKA'), 'Sri Lanka')
    expect_equal(name_of('LSO'), 'Lesotho')
    expect_equal(name_of('LTU'), 'Lithuania')
    expect_equal(name_of('LUX'), 'Luxembourg')
    expect_equal(name_of('LVA'), 'Latvia')
    expect_equal(name_of('MAC'), 'Macao')
    expect_equal(name_of('MAF'), 'Saint Martin (French part)')
    expect_equal(name_of('MAR'), 'Morocco')
    expect_equal(name_of('MCO'), 'Monaco')
    expect_equal(name_of('MDA'), 'Moldova, Republic of')
    expect_equal(name_of('MDG'), 'Madagascar')
    expect_equal(name_of('MDV'), 'Maldives')
    expect_equal(name_of('MEX'), 'Mexico')
    expect_equal(name_of('MHL'), 'Marshall Islands')
    expect_equal(name_of('MKD'), 'Macedonia, the former Yugoslav Republic of')
    expect_equal(name_of('MLI'), 'Mali')
    expect_equal(name_of('MLT'), 'Malta')
    expect_equal(name_of('MMR'), 'Myanmar')
    expect_equal(name_of('MNE'), 'Montenegro')
    expect_equal(name_of('MNG'), 'Mongolia')
    expect_equal(name_of('MNP'), 'Northern Mariana Islands')
    expect_equal(name_of('MOZ'), 'Mozambique')
    expect_equal(name_of('MRT'), 'Mauritania')
    expect_equal(name_of('MSR'), 'Montserrat')
    expect_equal(name_of('MTQ'), 'Martinique')
    expect_equal(name_of('MUS'), 'Mauritius')
    expect_equal(name_of('MWI'), 'Malawi')
    expect_equal(name_of('MYS'), 'Malaysia')
    expect_equal(name_of('MYT'), 'Mayotte')
    expect_equal(name_of('NAM'), 'Namibia')
    expect_equal(name_of('NCL'), 'New Caledonia')
    expect_equal(name_of('NER'), 'Niger')
    expect_equal(name_of('NFK'), 'Norfolk Island')
    expect_equal(name_of('NGA'), 'Nigeria')
    expect_equal(name_of('NIC'), 'Nicaragua')
    expect_equal(name_of('NIU'), 'Niue')
    expect_equal(name_of('NLD'), 'Netherlands')
    expect_equal(name_of('NOR'), 'Norway')
    expect_equal(name_of('NPL'), 'Nepal')
    expect_equal(name_of('NRU'), 'Nauru')
    expect_equal(name_of('NZL'), 'New Zealand')
    expect_equal(name_of('OMN'), 'Oman')
    expect_equal(name_of('PAK'), 'Pakistan')
    expect_equal(name_of('PAN'), 'Panama')
    expect_equal(name_of('PCN'), 'Pitcairn')
    expect_equal(name_of('PER'), 'Peru')
    expect_equal(name_of('PHL'), 'Philippines')
    expect_equal(name_of('PLW'), 'Palau')
    expect_equal(name_of('PNG'), 'Papua New Guinea')
    expect_equal(name_of('POL'), 'Poland')
    expect_equal(name_of('PRI'), 'Puerto Rico')
    expect_equal(name_of('PRK'), 'Korea, Democratic People\'s Republic of')
    expect_equal(name_of('PRT'), 'Portugal')
    expect_equal(name_of('PRY'), 'Paraguay')
    expect_equal(name_of('PSE'), 'Palestine, State of')
    expect_equal(name_of('PYF'), 'French Polynesia')
    expect_equal(name_of('QAT'), 'Qatar')
    expect_equal(name_of('REU'), 'Reunion')
    expect_equal(name_of('ROU'), 'Romania')
    expect_equal(name_of('RUS'), 'Russian Federation')
    expect_equal(name_of('RWA'), 'Rwanda')
    expect_equal(name_of('SAU'), 'Saudi Arabia')
    expect_equal(name_of('SDN'), 'Sudan')
    expect_equal(name_of('SEN'), 'Senegal')
    expect_equal(name_of('SGP'), 'Singapore')
    expect_equal(name_of('SGS'), 'South Georgia and the South Sandwich Islands')
    expect_equal(name_of('SHN'), 'Saint Helena, Ascension and Tristan da Cunha')
    expect_equal(name_of('SJM'), 'Svalbard and Jan Mayen')
    expect_equal(name_of('SLB'), 'Solomon Islands')
    expect_equal(name_of('SLE'), 'Sierra Leone')
    expect_equal(name_of('SLV'), 'El Salvador')
    expect_equal(name_of('SMR'), 'San Marino')
    expect_equal(name_of('SOM'), 'Somalia')
    expect_equal(name_of('SPM'), 'Saint Pierre and Miquelon')
    expect_equal(name_of('SRB'), 'Serbia')
    expect_equal(name_of('SSD'), 'South Sudan')
    expect_equal(name_of('STP'), 'Sao Tome and Principe')
    expect_equal(name_of('SUR'), 'Suriname')
    expect_equal(name_of('SVK'), 'Slovakia')
    expect_equal(name_of('SVN'), 'Slovenia')
    expect_equal(name_of('SWE'), 'Sweden')
    expect_equal(name_of('SWZ'), 'Swaziland')
    expect_equal(name_of('SXM'), 'Sint Maarten (Dutch part)')
    expect_equal(name_of('SYC'), 'Seychelles')
    expect_equal(name_of('SYR'), 'Syrian Arab Republic')
    expect_equal(name_of('TCA'), 'Turks and Caicos Islands')
    expect_equal(name_of('TCD'), 'Chad')
    expect_equal(name_of('TGO'), 'Togo')
    expect_equal(name_of('THA'), 'Thailand')
    expect_equal(name_of('TJK'), 'Tajikistan')
    expect_equal(name_of('TKL'), 'Tokelau')
    expect_equal(name_of('TKM'), 'Turkmenistan')
    expect_equal(name_of('TLS'), 'Timor-Leste')
    expect_equal(name_of('TON'), 'Tonga')
    expect_equal(name_of('TTO'), 'Trinidad and Tobago')
    expect_equal(name_of('TUN'), 'Tunisia')
    expect_equal(name_of('TUR'), 'Turkey')
    expect_equal(name_of('TUV'), 'Tuvalu')
    expect_equal(name_of('TWN'), 'Taiwan, Province of China')
    expect_equal(name_of('TZA'), 'Tanzania, United Republic of')
    expect_equal(name_of('UGA'), 'Uganda')
    expect_equal(name_of('UKR'), 'Ukraine')
    expect_equal(name_of('UMI'), 'United States Minor Outlying Islands')
    expect_equal(name_of('URY'), 'Uruguay')
    expect_equal(name_of('USA'), 'United States')
    expect_equal(name_of('UZB'), 'Uzbekistan')
    expect_equal(name_of('VAT'), 'Holy See (Vatican City State)')
    expect_equal(name_of('VCT'), 'Saint Vincent and the Grenadines')
    expect_equal(name_of('VEN'), 'Venezuela, Bolivarian Republic of')
    expect_equal(name_of('VGB'), 'Virgin Islands, British')
    expect_equal(name_of('VIR'), 'Virgin Islands, U.S.')
    expect_equal(name_of('VNM'), 'Viet Nam')
    expect_equal(name_of('VUT'), 'Vanuatu')
    expect_equal(name_of('WLF'), 'Wallis and Futuna')
    expect_equal(name_of('WSM'), 'Samoa')
    expect_equal(name_of('YEM'), 'Yemen')
    expect_equal(name_of('ZAF'), 'South Africa')
    expect_equal(name_of('ZMB'), 'Zambia')
    expect_equal(name_of('ZWE'), 'Zimbabwe')
})
