context('Special cases of regex')

iso3c_of <- function(name) countrycode(name, 'country.name', 'iso3c', warn = TRUE)

test_that('accented characters are properly matched', {
    expect_that(iso3c_of('Åland Islands'), matches('ALA'))
    expect_that(iso3c_of('Saint Barthélemy'), matches('BLM'))
    expect_that(iso3c_of('Côte d\'Ivoire'), matches('CIV'))
    expect_that(iso3c_of('Curaçao'), matches('CUW'))
    expect_that(iso3c_of('Réunion'), matches('REU'))
    expect_that(iso3c_of('São Tomé and Príncipe'), matches('STP'))
})

test_that('some official country names are properly matched', {
    expect_that(iso3c_of('democratic people\'s republic of korea'), matches('PRK'))
    expect_that(iso3c_of('republic of guinea'), matches('GIN'))
    expect_that(iso3c_of('hellenic republic'), matches('GRC'))
    expect_that(iso3c_of('united mexican states'), matches('MEX'))
    expect_that(iso3c_of('republic of the union of myanmar'), matches('MMR'))
    expect_that(iso3c_of('independent state of samoa'), matches('WSM'))
    expect_that(iso3c_of('republic of south sudan'), matches('SSD'))
    expect_that(iso3c_of('swiss confederation'), matches('CHE'))
})

test_that('some unofficial country names are properly matched', {
    expect_that(iso3c_of('dprk'), matches('PRK'))
    expect_that(iso3c_of('byelorussia'), matches('BLR'))
    expect_that(iso3c_of('british honduras'), matches('BLZ'))
    expect_that(iso3c_of('bechuanaland'), matches('BWA'))
    expect_that(iso3c_of('nyasaland'), matches('MWI'))
    expect_that(iso3c_of('british east africa'), matches('KEN'))
    expect_that(iso3c_of('east africa protectorate'), matches('KEN'))
    expect_that(iso3c_of('east pakistan'), matches('BGD'))
    expect_that(iso3c_of('chinese taipei'), matches('TWN'))
    expect_that(iso3c_of('taipei'), matches('TWN'))
})

test_that('former Soviet republics are properly matched', {
    expect_that(iso3c_of('russian soviet federative socialist republic'), matches('RUS'))
    expect_that(iso3c_of('ukrainian soviet socialist republic'), matches('UKR'))
    expect_that(iso3c_of('uzbek soviet socialist republic'), matches('UZB'))
    expect_that(iso3c_of('kazakh soviet socialist republic'), matches('KAZ'))
    expect_that(iso3c_of('byelorussian soviet socialist republic'), matches('BLR'))
    expect_that(iso3c_of('azerbaijan soviet socialist republic'), matches('AZE'))
    expect_that(iso3c_of('georgian soviet socialist republic'), matches('GEO'))
    expect_that(iso3c_of('tajik soviet socialist republic'), matches('TJK'))
    expect_that(iso3c_of('moldovian soviet socialist republic'), matches('MDA'))
    expect_that(iso3c_of('kirghiz soviet socialist republic'), matches('KGZ'))
    expect_that(iso3c_of('lithuanian soviet socialist republic'), matches('LTU'))
    expect_that(iso3c_of('turkmen soviet socialist republic'), matches('TKM'))
    expect_that(iso3c_of('armenian soviet socialist republic'), matches('ARM'))
    expect_that(iso3c_of('latvian soviet socialist republic'), matches('LVA'))
    expect_that(iso3c_of('estonian soviet socialist republic'), matches('EST'))
})

test_that('some common abbreviations are properly matched', {
    expect_that(iso3c_of('u.s.'), matches('USA'))
    expect_that(iso3c_of('u.s.a.'), matches('USA'))
    expect_that(iso3c_of('u.k.'), matches('GBR'))
    expect_that(iso3c_of('fyrom'), matches('MKD'))
    expect_that(iso3c_of('united arab em.'), matches('ARE'))
    expect_that(iso3c_of('united arab republic'), matches(NA_character_))
    expect_that(iso3c_of('emirates'), matches('ARE'))
    expect_that(iso3c_of('uae'), matches('ARE'))
    expect_that(iso3c_of('u.a.e.'), matches('ARE'))
})

test_that('the two Congos are distinguished', {
    expect_that(iso3c_of('republic of congo'), matches('COG'))
    expect_that(iso3c_of('republic of the congo'), matches('COG'))
    expect_that(iso3c_of('congo, republic of the'), matches('COG'))
    expect_that(iso3c_of('congo, republic'), matches('COG'))
    expect_that(iso3c_of('congo, rep.'), matches('COG'))
    expect_that(iso3c_of('ROC'), equals(NA_character_))   # Since ROC might mean Taiwan
    expect_that(iso3c_of('congo-brazzaville'), matches('COG'))
    expect_that(iso3c_of('french congo'), matches('COG'))
    
    expect_that(iso3c_of('democratic republic of the congo'), matches('COD'))
    expect_that(iso3c_of('congo, democratic republic of the'), matches('COD'))
    expect_that(iso3c_of('dem rep of the congo'), matches('COD'))
    expect_that(iso3c_of('the democratic republic of congo'), matches('COD'))
    expect_that(iso3c_of('congo, dem. rep.'), matches('COD'))
    expect_that(iso3c_of('dr congo'), matches('COD'))
    expect_that(iso3c_of('drc'), matches('COD'))
    expect_that(iso3c_of('droc'), matches('COD'))
    expect_that(iso3c_of('rdc'), matches('COD'))
    expect_that(iso3c_of('congo-kinshasa'), matches('COD'))
    expect_that(iso3c_of('congo-zaire'), matches('COD'))
    expect_that(iso3c_of('zaire'), matches('COD'))
    expect_that(iso3c_of('belgian congo'), matches('COD'))
    expect_that(iso3c_of('republic of the congo-léopoldville'), matches('COD'))
    expect_that(iso3c_of('congo free state'), matches('COD'))
})