context('External validity of regex')

iso3c_of <- function(name) countrycode(name, 'country.name', 'iso3c', warn = TRUE)

test_that('a variety of country names yield correct iso3c codes', {
    expect_that(iso3c_of('Aruba'), matches('ABW'))
    expect_that(iso3c_of('Afghanistan'), matches('AFG'))
    expect_that(iso3c_of('Angola'), matches('AGO'))
    expect_that(iso3c_of('Anguilla'), matches('AIA'))
    expect_that(iso3c_of('Åland Islands'), matches('ALA'))
    expect_that(iso3c_of('Albania'), matches('ALB'))
    expect_that(iso3c_of('Andorra'), matches('AND'))
    expect_that(iso3c_of('United Arab Emirates'), matches('ARE'))
    expect_that(iso3c_of('Argentina'), matches('ARG'))
    expect_that(iso3c_of('Armenia'), matches('ARM'))
    expect_that(iso3c_of('American Samoa'), matches('ASM'))
    expect_that(iso3c_of('Antarctica'), matches('ATA'))
    expect_that(iso3c_of('French Southern and Antarctic Lands'), matches('ATF'))
    expect_that(iso3c_of('Antigua and Barbuda'), matches('ATG'))
    expect_that(iso3c_of('Australia'), matches('AUS'))
    expect_that(iso3c_of('Austria'), matches('AUT'))
    expect_that(iso3c_of('Azerbaijan'), matches('AZE'))
    expect_that(iso3c_of('Burundi'), matches('BDI'))
    expect_that(iso3c_of('Belgium'), matches('BEL'))
    expect_that(iso3c_of('Benin'), matches('BEN'))
    expect_that(iso3c_of('Caribbean Netherlands'), matches('BES'))
    expect_that(iso3c_of('Burkina Faso'), matches('BFA'))
    expect_that(iso3c_of('Bangladesh'), matches('BGD'))
    expect_that(iso3c_of('Bulgaria'), matches('BGR'))
    expect_that(iso3c_of('Bahrain'), matches('BHR'))
    expect_that(iso3c_of('The Bahamas'), matches('BHS'))
    expect_that(iso3c_of('Bosnia and Herzegovina'), matches('BIH'))
    expect_that(iso3c_of('Saint Barthélemy'), matches('BLM'))
    expect_that(iso3c_of('Belarus'), matches('BLR'))
    expect_that(iso3c_of('Belize'), matches('BLZ'))
    expect_that(iso3c_of('Bermuda'), matches('BMU'))
    expect_that(iso3c_of('Bolivia'), matches('BOL'))
    expect_that(iso3c_of('Brazil'), matches('BRA'))
    expect_that(iso3c_of('Barbados'), matches('BRB'))
    expect_that(iso3c_of('Brunei'), matches('BRN'))
    expect_that(iso3c_of('Bhutan'), matches('BTN'))
    expect_that(iso3c_of('Bouvet Island'), matches('BVT'))
    expect_that(iso3c_of('Botswana'), matches('BWA'))
    expect_that(iso3c_of('Central African Republic'), matches('CAF'))
    expect_that(iso3c_of('Canada'), matches('CAN'))
    expect_that(iso3c_of('Cocos (Keeling) Islands'), matches('CCK'))
    expect_that(iso3c_of('Switzerland'), matches('CHE'))
    expect_that(iso3c_of('Chile'), matches('CHL'))
    expect_that(iso3c_of('China'), matches('CHN'))
    expect_that(iso3c_of('Côte d\'Ivoire'), matches('CIV'))
    expect_that(iso3c_of('Cameroon'), matches('CMR'))
    expect_that(iso3c_of('Democratic Republic of the Congo'), matches('COD'))
    expect_that(iso3c_of('Republic of the Congo'), matches('COG'))
    expect_that(iso3c_of('Cook Islands'), matches('COK'))
    expect_that(iso3c_of('Colombia'), matches('COL'))
    expect_that(iso3c_of('Comoros'), matches('COM'))
    expect_that(iso3c_of('Cabo Verde'), matches('CPV'))
    expect_that(iso3c_of('Costa Rica'), matches('CRI'))
    expect_that(iso3c_of('Cuba'), matches('CUB'))
    expect_that(iso3c_of('Curaçao'), matches('CUW'))
    expect_that(iso3c_of('Christmas Island'), matches('CXR'))
    expect_that(iso3c_of('Cayman Islands'), matches('CYM'))
    expect_that(iso3c_of('Cyprus'), matches('CYP'))
    expect_that(iso3c_of('Czech Republic'), matches('CZE'))
    expect_that(iso3c_of('Germany'), matches('DEU'))
    expect_that(iso3c_of('Djibouti'), matches('DJI'))
    expect_that(iso3c_of('Dominica'), matches('DMA'))
    expect_that(iso3c_of('Denmark'), matches('DNK'))
    expect_that(iso3c_of('Dominican Republic'), matches('DOM'))
    expect_that(iso3c_of('Algeria'), matches('DZA'))
    expect_that(iso3c_of('Ecuador'), matches('ECU'))
    expect_that(iso3c_of('Egypt'), matches('EGY'))
    expect_that(iso3c_of('Eritrea'), matches('ERI'))
    expect_that(iso3c_of('Western Sahara'), matches('ESH'))
    expect_that(iso3c_of('Spain'), matches('ESP'))
    expect_that(iso3c_of('Estonia'), matches('EST'))
    expect_that(iso3c_of('Ethiopia'), matches('ETH'))
    expect_that(iso3c_of('Finland'), matches('FIN'))
    expect_that(iso3c_of('Fiji'), matches('FJI'))
    expect_that(iso3c_of('Falkland Islands'), matches('FLK'))
    expect_that(iso3c_of('France'), matches('FRA'))
    expect_that(iso3c_of('Faroe Islands'), matches('FRO'))
    expect_that(iso3c_of('Federated States of Micronesia'), matches('FSM'))
    expect_that(iso3c_of('Gabon'), matches('GAB'))
    expect_that(iso3c_of('United Kingdom'), matches('GBR'))
    expect_that(iso3c_of('Georgia'), matches('GEO'))
    expect_that(iso3c_of('Guernsey'), matches('GGY'))
    expect_that(iso3c_of('Ghana'), matches('GHA'))
    expect_that(iso3c_of('Gibraltar'), matches('GIB'))
    expect_that(iso3c_of('Guinea'), matches('GIN'))
    expect_that(iso3c_of('Guadeloupe'), matches('GLP'))
    expect_that(iso3c_of('The Gambia'), matches('GMB'))
    expect_that(iso3c_of('Guinea-Bissau'), matches('GNB'))
    expect_that(iso3c_of('Equatorial Guinea'), matches('GNQ'))
    expect_that(iso3c_of('Greece'), matches('GRC'))
    expect_that(iso3c_of('Grenada'), matches('GRD'))
    expect_that(iso3c_of('Greenland'), matches('GRL'))
    expect_that(iso3c_of('Guatemala'), matches('GTM'))
    expect_that(iso3c_of('French Guiana'), matches('GUF'))
    expect_that(iso3c_of('Guam'), matches('GUM'))
    expect_that(iso3c_of('Guyana'), matches('GUY'))
    expect_that(iso3c_of('Hong Kong'), matches('HKG'))
    expect_that(iso3c_of('Heard Island and McDonald Islands'), matches('HMD'))
    expect_that(iso3c_of('Honduras'), matches('HND'))
    expect_that(iso3c_of('Croatia'), matches('HRV'))
    expect_that(iso3c_of('Haiti'), matches('HTI'))
    expect_that(iso3c_of('Hungary'), matches('HUN'))
    expect_that(iso3c_of('Indonesia'), matches('IDN'))
    expect_that(iso3c_of('Isle of Man'), matches('IMN'))
    expect_that(iso3c_of('India'), matches('IND'))
    expect_that(iso3c_of('British Indian Ocean Territory'), matches('IOT'))
    expect_that(iso3c_of('Republic of Ireland'), matches('IRL'))
    expect_that(iso3c_of('Iran'), matches('IRN'))
    expect_that(iso3c_of('Iraq'), matches('IRQ'))
    expect_that(iso3c_of('Iceland'), matches('ISL'))
    expect_that(iso3c_of('Israel'), matches('ISR'))
    expect_that(iso3c_of('Italy'), matches('ITA'))
    expect_that(iso3c_of('Jamaica'), matches('JAM'))
    expect_that(iso3c_of('Jersey'), matches('JEY'))
    expect_that(iso3c_of('Jordan'), matches('JOR'))
    expect_that(iso3c_of('Japan'), matches('JPN'))
    expect_that(iso3c_of('Kazakhstan'), matches('KAZ'))
    expect_that(iso3c_of('Kenya'), matches('KEN'))
    expect_that(iso3c_of('Kyrgyzstan'), matches('KGZ'))
    expect_that(iso3c_of('Cambodia'), matches('KHM'))
    expect_that(iso3c_of('Kiribati'), matches('KIR'))
    expect_that(iso3c_of('Saint Kitts and Nevis'), matches('KNA'))
    expect_that(iso3c_of('South Korea'), matches('KOR'))
    expect_that(iso3c_of('Kuwait'), matches('KWT'))
    expect_that(iso3c_of('Laos'), matches('LAO'))
    expect_that(iso3c_of('Lebanon'), matches('LBN'))
    expect_that(iso3c_of('Liberia'), matches('LBR'))
    expect_that(iso3c_of('Libya'), matches('LBY'))
    expect_that(iso3c_of('Saint Lucia'), matches('LCA'))
    expect_that(iso3c_of('Liechtenstein'), matches('LIE'))
    expect_that(iso3c_of('Sri Lanka'), matches('LKA'))
    expect_that(iso3c_of('Lesotho'), matches('LSO'))
    expect_that(iso3c_of('Lithuania'), matches('LTU'))
    expect_that(iso3c_of('Luxembourg'), matches('LUX'))
    expect_that(iso3c_of('Latvia'), matches('LVA'))
    expect_that(iso3c_of('Macau'), matches('MAC'))
    expect_that(iso3c_of('Collectivity of Saint Martin'), matches('MAF'))
    expect_that(iso3c_of('Morocco'), matches('MAR'))
    expect_that(iso3c_of('Monaco'), matches('MCO'))
    expect_that(iso3c_of('Moldova'), matches('MDA'))
    expect_that(iso3c_of('Madagascar'), matches('MDG'))
    expect_that(iso3c_of('Maldives'), matches('MDV'))
    expect_that(iso3c_of('Mexico'), matches('MEX'))
    expect_that(iso3c_of('Marshall Islands'), matches('MHL'))
    expect_that(iso3c_of('Republic of Macedonia'), matches('MKD'))
    expect_that(iso3c_of('Mali'), matches('MLI'))
    expect_that(iso3c_of('Malta'), matches('MLT'))
    expect_that(iso3c_of('Myanmar'), matches('MMR'))
    expect_that(iso3c_of('Montenegro'), matches('MNE'))
    expect_that(iso3c_of('Mongolia'), matches('MNG'))
    expect_that(iso3c_of('Northern Mariana Islands'), matches('MNP'))
    expect_that(iso3c_of('Mozambique'), matches('MOZ'))
    expect_that(iso3c_of('Mauritania'), matches('MRT'))
    expect_that(iso3c_of('Montserrat'), matches('MSR'))
    expect_that(iso3c_of('Martinique'), matches('MTQ'))
    expect_that(iso3c_of('Mauritius'), matches('MUS'))
    expect_that(iso3c_of('Malawi'), matches('MWI'))
    expect_that(iso3c_of('Malaysia'), matches('MYS'))
    expect_that(iso3c_of('Mayotte'), matches('MYT'))
    expect_that(iso3c_of('Namibia'), matches('NAM'))
    expect_that(iso3c_of('New Caledonia'), matches('NCL'))
    expect_that(iso3c_of('Niger'), matches('NER'))
    expect_that(iso3c_of('Norfolk Island'), matches('NFK'))
    expect_that(iso3c_of('Nigeria'), matches('NGA'))
    expect_that(iso3c_of('Nicaragua'), matches('NIC'))
    expect_that(iso3c_of('Niue'), matches('NIU'))
    expect_that(iso3c_of('Netherlands'), matches('NLD'))
    expect_that(iso3c_of('Norway'), matches('NOR'))
    expect_that(iso3c_of('Nepal'), matches('NPL'))
    expect_that(iso3c_of('Nauru'), matches('NRU'))
    expect_that(iso3c_of('New Zealand'), matches('NZL'))
    expect_that(iso3c_of('Oman'), matches('OMN'))
    expect_that(iso3c_of('Pakistan'), matches('PAK'))
    expect_that(iso3c_of('Panama'), matches('PAN'))
    expect_that(iso3c_of('Pitcairn Islands'), matches('PCN'))
    expect_that(iso3c_of('Peru'), matches('PER'))
    expect_that(iso3c_of('Philippines'), matches('PHL'))
    expect_that(iso3c_of('Palau'), matches('PLW'))
    expect_that(iso3c_of('Papua New Guinea'), matches('PNG'))
    expect_that(iso3c_of('Poland'), matches('POL'))
    expect_that(iso3c_of('Puerto Rico'), matches('PRI'))
    expect_that(iso3c_of('North Korea'), matches('PRK'))
    expect_that(iso3c_of('Portugal'), matches('PRT'))
    expect_that(iso3c_of('Paraguay'), matches('PRY'))
    expect_that(iso3c_of('State of Palestine'), matches('PSE'))
    expect_that(iso3c_of('French Polynesia'), matches('PYF'))
    expect_that(iso3c_of('Qatar'), matches('QAT'))
    expect_that(iso3c_of('Réunion'), matches('REU'))
    expect_that(iso3c_of('Romania'), matches('ROU'))
    expect_that(iso3c_of('Russia'), matches('RUS'))
    expect_that(iso3c_of('Rwanda'), matches('RWA'))
    expect_that(iso3c_of('Saudi Arabia'), matches('SAU'))
    expect_that(iso3c_of('Sudan'), matches('SDN'))
    expect_that(iso3c_of('Senegal'), matches('SEN'))
    expect_that(iso3c_of('Singapore'), matches('SGP'))
    expect_that(iso3c_of('South Georgia and the South Sandwich Islands'), matches('SGS'))
    expect_that(iso3c_of('Saint Helena, Ascension and Tristan da Cunha'), matches('SHN'))
    expect_that(iso3c_of('Svalbard and Jan Mayen'), matches('SJM'))
    expect_that(iso3c_of('Solomon Islands'), matches('SLB'))
    expect_that(iso3c_of('Sierra Leone'), matches('SLE'))
    expect_that(iso3c_of('El Salvador'), matches('SLV'))
    expect_that(iso3c_of('San Marino'), matches('SMR'))
    expect_that(iso3c_of('Somalia'), matches('SOM'))
    expect_that(iso3c_of('Saint Pierre and Miquelon'), matches('SPM'))
    expect_that(iso3c_of('Serbia'), matches('SRB'))
    expect_that(iso3c_of('South Sudan'), matches('SSD'))
    expect_that(iso3c_of('São Tomé and Príncipe'), matches('STP'))
    expect_that(iso3c_of('Suriname'), matches('SUR'))
    expect_that(iso3c_of('Slovakia'), matches('SVK'))
    expect_that(iso3c_of('Slovenia'), matches('SVN'))
    expect_that(iso3c_of('Sweden'), matches('SWE'))
    expect_that(iso3c_of('Swaziland'), matches('SWZ'))
    expect_that(iso3c_of('Sint Maarten'), matches('SXM'))
    expect_that(iso3c_of('Seychelles'), matches('SYC'))
    expect_that(iso3c_of('Syria'), matches('SYR'))
    expect_that(iso3c_of('Turks and Caicos Islands'), matches('TCA'))
    expect_that(iso3c_of('Chad'), matches('TCD'))
    expect_that(iso3c_of('Togo'), matches('TGO'))
    expect_that(iso3c_of('Thailand'), matches('THA'))
    expect_that(iso3c_of('Tajikistan'), matches('TJK'))
    expect_that(iso3c_of('Tokelau'), matches('TKL'))
    expect_that(iso3c_of('Turkmenistan'), matches('TKM'))
    expect_that(iso3c_of('East Timor'), matches('TLS'))
    expect_that(iso3c_of('Tonga'), matches('TON'))
    expect_that(iso3c_of('Trinidad and Tobago'), matches('TTO'))
    expect_that(iso3c_of('Tunisia'), matches('TUN'))
    expect_that(iso3c_of('Turkey'), matches('TUR'))
    expect_that(iso3c_of('Tuvalu'), matches('TUV'))
    expect_that(iso3c_of('Taiwan'), matches('TWN'))
    expect_that(iso3c_of('Tanzania'), matches('TZA'))
    expect_that(iso3c_of('Uganda'), matches('UGA'))
    expect_that(iso3c_of('Ukraine'), matches('UKR'))
    expect_that(iso3c_of('United States Minor Outlying Islands'), matches('UMI'))
    expect_that(iso3c_of('Uruguay'), matches('URY'))
    expect_that(iso3c_of('United States'), matches('USA'))
    expect_that(iso3c_of('Uzbekistan'), matches('UZB'))
    expect_that(iso3c_of('Vatican City'), matches('VAT'))
    expect_that(iso3c_of('Saint Vincent and the Grenadines'), matches('VCT'))
    expect_that(iso3c_of('Venezuela'), matches('VEN'))
    expect_that(iso3c_of('British Virgin Islands'), matches('VGB'))
    expect_that(iso3c_of('United States Virgin Islands'), matches('VIR'))
    expect_that(iso3c_of('Viet Nam'), matches('VNM'))
    expect_that(iso3c_of('Vanuatu'), matches('VUT'))
    expect_that(iso3c_of('Wallis and Futuna'), matches('WLF'))
    expect_that(iso3c_of('Samoa'), matches('WSM'))
    expect_that(iso3c_of('Yemen'), matches('YEM'))
    expect_that(iso3c_of('South Africa'), matches('ZAF'))
    expect_that(iso3c_of('Zambia'), matches('ZMB'))
    expect_that(iso3c_of('Zimbabwe'), matches('ZWE'))
})